In [1]:
#initial Imports
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
#files to load
GDP_per_capita_file_path = ("Resources/GDP_per_capita.csv")

## Clean GDP data

In [3]:
# read in file
GDP_data = pd.read_csv(GDP_per_capita_file_path)
df = pd.DataFrame(GDP_data)
df

,Series Name,Series Code,Country Name,Country Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021]
0,GDP per capita (current US$),NY.GDP.PCAP.CD,Afghanistan,AFG,59.7732337032148,59.8608999923829,58.4580086983139,78.7064287776753,82.0953065340517,101.108325163758,...,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029,516.747870807558,..
1,GDP per capita (current US$),NY.GDP.PCAP.CD,Albania,ALB,..,..,..,..,..,..,...,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732,5332.16047456847,6494.38571288581
2,GDP per capita (current US$),NY.GDP.PCAP.CD,Algeria,DZA,246.303751319472,214.771980100889,172.242508957181,226.895450128271,238.0437103942,249.883585607009,...,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236,3306.85820838104,3765.03462494702
3,GDP per capita (current US$),NY.GDP.PCAP.CD,American Samoa,ASM,..,..,..,..,..,..,...,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487,12844.9009909959,..
4,GDP per capita (current US$),NY.GDP.PCAP.CD,Andorra,AND,..,..,..,..,..,..,...,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904,37416.6977203275,43047.6862704034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,Last Updated: 09/16/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['Series Name', 'Series Code', 'Country Name', 'Country Code',
       '1960 [YR1960]', '1961 [YR1961]', '1962 [YR1962]', '1963 [YR1963]',
       '1964 [YR1964]', '1965 [YR1965]', '1966 [YR1966]', '1967 [YR1967]',
       '1968 [YR1968]', '1969 [YR1969]', '1970 [YR1970]', '1971 [YR1971]',
       '1972 [YR1972]', '1973 [YR1973]', '1974 [YR1974]', '1975 [YR1975]',
       '1976 [YR1976]', '1977 [YR1977]', '1978 [YR1978]', '1979 [YR1979]',
       '1980 [YR1980]', '1981 [YR1981]', '1982 [YR1982]', '1983 [YR1983]',
       '1984 [YR1984]', '1985 [YR1985]', '1986 [YR1986]', '1987 [YR1987]',
       '1988 [YR1988]', '1989 [YR1989]', '1990 [YR1990]', '1991 [YR1991]',
       '1992 [YR1992]', '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]',
       '1996 [YR1996]', '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]',
       '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]',
       '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]',
       '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]'],
      dtype='object')>

In [5]:
df = df.drop(df.columns[4:45], axis=1)
df

,Series Name,Series Code,Country Name,Country Code,2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021]
0,GDP per capita (current US$),NY.GDP.PCAP.CD,Afghanistan,AFG,..,179.426579211394,190.683814295088,211.382074198939,242.031313175022,263.733601866274,...,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029,516.747870807558,..
1,GDP per capita (current US$),NY.GDP.PCAP.CD,Albania,ALB,1281.6598256178,1425.12421860142,1846.12012081207,2373.58129170055,2673.78658429559,2972.74292399799,...,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732,5332.16047456847,6494.38571288581
2,GDP per capita (current US$),NY.GDP.PCAP.CD,Algeria,DZA,1740.60665427662,1781.82890798394,2103.38129106939,2610.18542243488,3113.09488313746,3478.71000237566,...,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236,3306.85820838104,3765.03462494702
3,GDP per capita (current US$),NY.GDP.PCAP.CD,American Samoa,ASM,..,8666.65538195914,8807.46281200101,8528.24877689163,8395.31877025371,8340.52343974691,...,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487,12844.9009909959,..
4,GDP per capita (current US$),NY.GDP.PCAP.CD,Andorra,AND,22970.5122133619,25067.2400639132,32272.8458909877,37966.1872524395,40064.2249292197,42674.7589681092,...,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904,37416.6977203275,43047.6862704034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,Last Updated: 09/16/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df.drop(df.columns[0:2], axis=1)
df

,Country Name,Country Code,2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],...,2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021]
0,Afghanistan,AFG,..,179.426579211394,190.683814295088,211.382074198939,242.031313175022,263.733601866274,359.693157866109,364.6635420423,...,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029,516.747870807558,..
1,Albania,ALB,1281.6598256178,1425.12421860142,1846.12012081207,2373.58129170055,2673.78658429559,2972.74292399799,3595.03805682893,4370.5399247769,...,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732,5332.16047456847,6494.38571288581
2,Algeria,DZA,1740.60665427662,1781.82890798394,2103.38129106939,2610.18542243488,3113.09488313746,3478.71000237566,3950.5129931247,4923.63161541179,...,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236,3306.85820838104,3765.03462494702
3,American Samoa,ASM,..,8666.65538195914,8807.46281200101,8528.24877689163,8395.31877025371,8340.52343974691,8874.87792759607,9740.82449121586,...,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487,12844.9009909959,..
4,Andorra,AND,22970.5122133619,25067.2400639132,32272.8458909877,37966.1872524395,40064.2249292197,42674.7589681092,47804.8499340211,48719.6587699036,...,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904,37416.6977203275,43047.6862704034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:

df = df.drop(df.columns[21:23], axis=1)
df

,Country Name,Country Code,2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],...,2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019]
0,Afghanistan,AFG,..,179.426579211394,190.683814295088,211.382074198939,242.031313175022,263.733601866274,359.693157866109,364.6635420423,...,543.306526178281,591.190030208565,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029
1,Albania,ALB,1281.6598256178,1425.12421860142,1846.12012081207,2373.58129170055,2673.78658429559,2972.74292399799,3595.03805682893,4370.5399247769,...,4094.34838574494,4437.14261222684,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732
2,Algeria,DZA,1740.60665427662,1781.82890798394,2103.38129106939,2610.18542243488,3113.09488313746,3478.71000237566,3950.5129931247,4923.63161541179,...,4480.78631766464,5455.67940349747,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236
3,American Samoa,ASM,..,8666.65538195914,8807.46281200101,8528.24877689163,8395.31877025371,8340.52343974691,8874.87792759607,9740.82449121586,...,10216.8176306968,10223.2983588916,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487
4,Andorra,AND,22970.5122133619,25067.2400639132,32272.8458909877,37966.1872524395,40064.2249292197,42674.7589681092,47804.8499340211,48719.6587699036,...,40849.7612766794,43333.9730414795,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['Country Name', 'Country Code', '2001 [YR2001]', '2002 [YR2002]',
       '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]',
       '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]',
       '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]',
       '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]',
       '2019 [YR2019]'],
      dtype='object')>

In [9]:
df = df.set_axis(['country_name', 'country_code', 'gpc_2001', 'gpc_2002','gpc_2003','gpc_2004','gpc_2005','gpc_2006',
                                            'gpc_2007','gpc_2008','gpc_2009','gpc_2010','gpc_2011','gpc_2012','gpc_2013','gpc_2014','gpc_2015','gpc_2016','gpc_2017',
                                            'gpc_2018','gpc_2019'], axis = 1, inplace=False)
df

,country_name,country_code,gpc_2001,gpc_2002,gpc_2003,gpc_2004,gpc_2005,gpc_2006,gpc_2007,gpc_2008,...,gpc_2010,gpc_2011,gpc_2012,gpc_2013,gpc_2014,gpc_2015,gpc_2016,gpc_2017,gpc_2018,gpc_2019
0,Afghanistan,AFG,..,179.426579211394,190.683814295088,211.382074198939,242.031313175022,263.733601866274,359.693157866109,364.6635420423,...,543.306526178281,591.190030208565,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029
1,Albania,ALB,1281.6598256178,1425.12421860142,1846.12012081207,2373.58129170055,2673.78658429559,2972.74292399799,3595.03805682893,4370.5399247769,...,4094.34838574494,4437.14261222684,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732
2,Algeria,DZA,1740.60665427662,1781.82890798394,2103.38129106939,2610.18542243488,3113.09488313746,3478.71000237566,3950.5129931247,4923.63161541179,...,4480.78631766464,5455.67940349747,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236
3,American Samoa,ASM,..,8666.65538195914,8807.46281200101,8528.24877689163,8395.31877025371,8340.52343974691,8874.87792759607,9740.82449121586,...,10216.8176306968,10223.2983588916,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487
4,Andorra,AND,22970.5122133619,25067.2400639132,32272.8458909877,37966.1872524395,40064.2249292197,42674.7589681092,47804.8499340211,48719.6587699036,...,40849.7612766794,43333.9730414795,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.dropna()
df

,country_name,country_code,gpc_2001,gpc_2002,gpc_2003,gpc_2004,gpc_2005,gpc_2006,gpc_2007,gpc_2008,...,gpc_2010,gpc_2011,gpc_2012,gpc_2013,gpc_2014,gpc_2015,gpc_2016,gpc_2017,gpc_2018,gpc_2019
0,Afghanistan,AFG,..,179.426579211394,190.683814295088,211.382074198939,242.031313175022,263.733601866274,359.693157866109,364.6635420423,...,543.306526178281,591.190030208565,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029
1,Albania,ALB,1281.6598256178,1425.12421860142,1846.12012081207,2373.58129170055,2673.78658429559,2972.74292399799,3595.03805682893,4370.5399247769,...,4094.34838574494,4437.14261222684,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732
2,Algeria,DZA,1740.60665427662,1781.82890798394,2103.38129106939,2610.18542243488,3113.09488313746,3478.71000237566,3950.5129931247,4923.63161541179,...,4480.78631766464,5455.67940349747,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236
3,American Samoa,ASM,..,8666.65538195914,8807.46281200101,8528.24877689163,8395.31877025371,8340.52343974691,8874.87792759607,9740.82449121586,...,10216.8176306968,10223.2983588916,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487
4,Andorra,AND,22970.5122133619,25067.2400639132,32272.8458909877,37966.1872524395,40064.2249292197,42674.7589681092,47804.8499340211,48719.6587699036,...,40849.7612766794,43333.9730414795,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Sub-Saharan Africa,SSF,594.434444321552,629.455425620411,772.769761067037,935.764934770637,1082.21416238718,1242.00009288337,1400.86266899238,1548.95537067417,...,1670.55403153336,1830.88264526029,1852.84089188473,1913.7372257658,1928.53420210314,1692.67429410075,1538.24441673708,1622.98261366666,1606.86341924427,1618.92077064802
262,Sub-Saharan Africa (excluding high income),SSA,593.587328337264,628.52817097875,771.872371855746,934.727384944081,1081.11554215438,1240.82572535565,1399.71748166849,1547.94355305383,...,1669.61066543265,1829.86873435934,1851.8651283776,1912.51133731048,1927.28388723456,1691.41056609812,1536.92933133768,1621.6323409707,1605.49002331914,1617.54193226682
263,Sub-Saharan Africa (IDA & IBRD countries),TSS,594.434444321552,629.455425620411,772.769761067037,935.764934770636,1082.21416238718,1242.00009288337,1400.86266899238,1548.95537067417,...,1670.55403153336,1830.88264526029,1852.84089188473,1913.7372257658,1928.53420210314,1692.67429410075,1538.24441673709,1622.98261366666,1606.86341924427,1618.92077064803
264,Upper middle income,UMC,1964.54933863313,1962.96178694351,2181.08595446151,2595.0891462929,3095.98478470738,3652.25334911503,4493.65237669287,5443.19266403504,...,6300.08541246828,7556.48341993734,8031.9362100123,8551.33613541085,8746.2657033762,8149.75183997258,8041.06232407941,8834.5262262122,9448.6348536615,9548.20023835792
265,World,WLD,5427.39118901622,5565.59251398012,6163.07895523448,6859.58398547951,7337.48982179067,7854.10439590898,8743.39603276206,9489.96601219516,...,9621.12828842617,10544.875810483,10648.2372249605,10815.5800128167,10976.383454178,10231.7025852204,10286.4113296305,10825.9023691211,11366.0736692165,11407.4793339488

In [11]:
df.isnull().sum()

country_name    0
country_code    0
gpc_2001        0
gpc_2002        0
gpc_2003        0
gpc_2004        0
gpc_2005        0
gpc_2006        0
gpc_2007        0
gpc_2008        0
gpc_2009        0
gpc_2010        0
gpc_2011        0
gpc_2012        0
gpc_2013        0
gpc_2014        0
gpc_2015        0
gpc_2016        0
gpc_2017        0
gpc_2018        0
gpc_2019        0
dtype: int64

In [12]:
df['country_name'].tolist()

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas, The',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt, Arab Rep.',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Polynesia',
 'Gabon',
 'Gambia, The',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong SAR, China',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran, Islamic Rep.',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 "Korea, Dem. People's Rep.",
 'Korea, Rep.',
 'Kosovo',
 'Kuwait',
 'Kyrgyz Republic',
 'Lao PDR',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao SAR, China',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Fed. Sts.',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovak Republic',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Martin (French part)',
 'St. Vincent and the Grenadines',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkiye',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela, RB',
 'Vietnam',
 'Virgin Islands (U.S.)',
 'West Bank and Gaza',
 'Yemen, Rep.',
 'Zambia',
 'Zimbabwe',
 'Africa Eastern and Southern',
 'Africa Western and Central',
 'Arab World',
 'Caribbean small states',
 'Central Europe and the Baltics',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'European Union',
 'Fragile and conflict affected situations',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Least developed countries: UN classification',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Middle East & North Africa',
 'Middle East & North Africa (excluding high income)',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle income',
 'North America',
 'Not classified',
 'OECD members',
 'Other small states',
 'Pacific island small states',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Small states',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (excluding high income)',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Upper middle income',
 'World']

In [13]:
#drop columns that are not countries
#a. set first column as axis
df = df.set_index(df["country_name"])
df

,country_name,country_code,gpc_2001,gpc_2002,gpc_2003,gpc_2004,gpc_2005,gpc_2006,gpc_2007,gpc_2008,...,gpc_2010,gpc_2011,gpc_2012,gpc_2013,gpc_2014,gpc_2015,gpc_2016,gpc_2017,gpc_2018,gpc_2019
country_name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Afghanistan,AFG,..,179.426579211394,190.683814295088,211.382074198939,242.031313175022,263.733601866274,359.693157866109,364.6635420423,...,543.306526178281,591.190030208565,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029
Albania,Albania,ALB,1281.6598256178,1425.12421860142,1846.12012081207,2373.58129170055,2673.78658429559,2972.74292399799,3595.03805682893,4370.5399247769,...,4094.34838574494,4437.14261222684,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732
Algeria,Algeria,DZA,1740.60665427662,1781.82890798394,2103.38129106939,2610.18542243488,3113.09488313746,3478.71000237566,3950.5129931247,4923.63161541179,...,4480.78631766464,5455.67940349747,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236
American Samoa,American Samoa,ASM,..,8666.65538195914,8807.46281200101,8528.24877689163,8395.31877025371,8340.52343974691,8874.87792759607,9740.82449121586,...,10216.8176306968,10223.2983588916,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487
Andorra,Andorra,AND,22970.5122133619,25067.2400639132,32272.8458909877,37966.1872524395,40064.2249292197,42674.7589681092,47804.8499340211,48719.6587699036,...,40849.7612766794,43333.9730414795,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sub-Saharan Africa,Sub-Saharan Africa,SSF,594.434444321552,629.455425620411,772.769761067037,935.764934770637,1082.21416238718,1242.00009288337,1400.86266899238,1548.95537067417,...,1670.55403153336,1830.88264526029,1852.84089188473,1913.7372257658,1928.53420210314,1692.67429410075,1538.24441673708,1622.98261366666,1606.86341924427,1618.92077064802
Sub-Saharan Africa (excluding high income),Sub-Saharan Africa (excluding high income),SSA,593.587328337264,628.52817097875,771.872371855746,934.727384944081,1081.11554215438,1240.82572535565,1399.71748166849,1547.94355305383,...,1669.61066543265,1829.86873435934,1851.8651283776,1912.51133731048,1927.28388723456,1691.41056609812,1536.92933133768,1621.6323409707,1605.49002331914,1617.54193226682
Sub-Saharan Africa (IDA & IBRD countries),Sub-Saharan Africa (IDA & IBRD countries),TSS,594.434444321552,629.455425620411,772.769761067037,935.764934770636,1082.21416238718,1242.00009288337,1400.86266899238,1548.95537067417,...,1670.55403153336,1830.88264526029,1852.84089188473,1913.7372257658,1928.53420210314,1692.67429410075,1538.24441673709,1622.98261366666,1606.86341924427,1618.92077064803
Upper middle income,Upper middle income,UMC,1964.54933863313,1962.96178694351,2181.08595446151,2595.0891462929,3095.98478470738,3652.25334911503,4493.65237669287,5443.19266403504,...,6300.08541246828,7556.48341993734,8031.9362100123,8551.33613541085,8746.2657033762,8149.75183997258,8041.06232407941,8834.5262262122,9448.6348536615,9548.20023835792
World,World,WLD,5427.39118901622,5565.59251398012,6163.07895523448,6859.58398547951,7337.48982179067,7854.10439590898,8743.39603276206,9489.96601219516,...,9621.12828842617,10544.875810483,10648.2372249605,10815.5800128167,10976.383454178,10231.7025852204,10286.4113296305,10825.9023691211,11366.0736692165,11407.4793339488

In [14]:
df = df.drop(labels=[
 'Africa Eastern and Southern',
 'Africa Western and Central',
 'Arab World',
 'Caribbean small states',
 'Central Europe and the Baltics',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'European Union',
 'Fragile and conflict affected situations',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Least developed countries: UN classification',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Middle East & North Africa',
 'Middle East & North Africa (excluding high income)',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle income',
 'North America',
 'Not classified',
 'OECD members',
 'Other small states',
 'Pacific island small states',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Small states',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (excluding high income)',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Upper middle income',
 'World'],axis=0, inplace= False)

In [15]:
df = df.dropna()
df

,country_name,country_code,gpc_2001,gpc_2002,gpc_2003,gpc_2004,gpc_2005,gpc_2006,gpc_2007,gpc_2008,...,gpc_2010,gpc_2011,gpc_2012,gpc_2013,gpc_2014,gpc_2015,gpc_2016,gpc_2017,gpc_2018,gpc_2019
country_name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Afghanistan,AFG,..,179.426579211394,190.683814295088,211.382074198939,242.031313175022,263.733601866274,359.693157866109,364.6635420423,...,543.306526178281,591.190030208565,638.845851607289,624.315454506615,614.223342360392,556.007220861443,512.012778129357,516.679862210543,485.668418729808,494.179349886029
Albania,Albania,ALB,1281.6598256178,1425.12421860142,1846.12012081207,2373.58129170055,2673.78658429559,2972.74292399799,3595.03805682893,4370.5399247769,...,4094.34838574494,4437.14261222684,4247.63004748194,4413.06200528903,4578.63320812155,3952.80253807527,4124.05538986272,4531.0193737689,5287.66369446913,5396.21586434732
Algeria,Algeria,DZA,1740.60665427662,1781.82890798394,2103.38129106939,2610.18542243488,3113.09488313746,3478.71000237566,3950.5129931247,4923.63161541179,...,4480.78631766464,5455.67940349747,5592.22011465753,5499.58733105334,5493.05669453687,4177.8895415169,3946.45244712537,4109.69821695727,4142.01855842917,3989.66827645236
American Samoa,American Samoa,ASM,..,8666.65538195914,8807.46281200101,8528.24877689163,8395.31877025371,8340.52343974691,8874.87792759607,9740.82449121586,...,10216.8176306968,10223.2983588916,11496.5240977923,11450.7241954879,11525.1563872309,12059.6351646776,12038.2496994923,11003.8297642807,11521.6097798453,11715.3601388487
Andorra,Andorra,AND,22970.5122133619,25067.2400639132,32272.8458909877,37966.1872524395,40064.2249292197,42674.7589681092,47804.8499340211,48719.6587699036,...,40849.7612766794,43333.9730414795,38684.5665299216,39538.3552064403,41302.3821426181,35770.9186530024,37474.7458403618,38964.662014361,41793.3188365378,40898.4179063904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands (U.S.),Virgin Islands (U.S.),VIR,..,30062.0225050457,31731.2566241187,35006.3614404514,40828.7460927775,41377.1466009652,44158.5054044325,39152.3750657306,...,39905.1284180994,38997.1373164651,37795.3192590675,34597.9766940328,33045.3643795999,34007.3529411765,35324.9748874586,35365.0693039774,36653.8630480089,38596.0307118282
West Bank and Gaza,West Bank and Gaza,PSE,1335.55319529359,1156.21747345769,1257.69857009689,1422.19088643544,1543.70141392774,1570.10439962728,1664.24571669276,2035.20234121766,...,2557.07562356699,2880.79843707909,3067.43872735614,3315.29753909282,3352.11259506043,3272.15432360708,3527.61382413178,3620.36048715937,3562.33094270256,3656.85827137011
"Yemen, Rep.","Yemen, Rep.",YEM,550.360364536532,579.853140602094,620.382725994575,709.96537880616,832.844198687909,921.418354862175,1017.29204849729,1229.24667476708,...,1334.78490225941,1374.62140060517,1446.53647172899,1607.15217325898,1674.00257166372,1601.80716299947,1152.73801930955,964.340343636774,758.145948927092,750.554583376727
Zambia,Zambia,ZMB,382.941035235257,382.241963342278,435.458199377947,538.591553038374,702.741118447779,1047.9188431217,1124.29058597692,1394.00049997193,...,1489.45908689417,1672.90753526193,1763.06944249903,1878.34681050661,1762.42781692474,1338.29092708188,1280.80654257604,1535.19657398198,1516.36837125728,1305.00103080403
Zimbabwe,Zimbabwe,ZWE,568.386290532649,530.53044625893,478.007604434538,482.998451486038,476.555402524382,447.854739946441,431.787258728843,356.693234400305,...,948.331481033457,1093.65340855817,1304.96801065699,1429.99846146678,1434.89627731806,1445.06970213198,1464.58895715841,1235.18903192064,1254.64226494434,1316.74065692871

In [16]:
#check null values
df.isna().sum()

country_name    0
country_code    0
gpc_2001        0
gpc_2002        0
gpc_2003        0
gpc_2004        0
gpc_2005        0
gpc_2006        0
gpc_2007        0
gpc_2008        0
gpc_2009        0
gpc_2010        0
gpc_2011        0
gpc_2012        0
gpc_2013        0
gpc_2014        0
gpc_2015        0
gpc_2016        0
gpc_2017        0
gpc_2018        0
gpc_2019        0
dtype: int64

In [17]:
df['gpc_2001'].tolist()

['..',
 '1281.6598256178',
 '1740.60665427662',
 '..',
 '22970.5122133619',
 '527.333528536691',
 '10367.3196068161',
 '7208.37311355372',
 '694.423455373229',
 '20417.7759623298',
 '19527.3235767954',
 '24558.7636778868',
 '703.683843432722',
 '27486.2367737544',
 '12868.1769170821',
 '415.034404287378',
 '11209.4211248688',
 '1244.37318523431',
 '23015.0712632462',
 '3417.09022428717',
 '518.067474134696',
 '58883.9594265967',
 '764.432808246182',
 '948.870204281826',
 '1544.60207235926',
 '3278.01607934706',
 '3160.24934491441',
 '..',
 '16472.0032948215',
 '1770.91353394746',
 '267.097599629023',
 '134.363426917623',
 '1292.22651152195',
 '321.150223642203',
 '687.648134393621',
 '23822.0601178964',
 '..',
 '250.576194304531',
 '197.146082103195',
 '41807.079018288',
 '4609.21396034224',
 '1053.10824300262',
 '2439.68245582205',
 '680.905572824133',
 '153.591044080197',
 '869.100509658205',
 '3960.30770307437',
 '997.478784298968',
 '5412.92513590593',
 '2837.73573008299',
 '..',
 '14821.447265625',
 '6637.04165713981',
 '30751.654348268',
 '780.903961316367',
 '4883.00302426696',
 '2977.43451003068',
 '1894.61619585804',
 '1378.20338333845',
 '2072.3015906358',
 '2313.16593689273',
 '316.823953429739',
 '4505.85833233188',
 '1521.76907531716',
 '120.765783730897',
 '24724.4579532836',
 '2030.24635131517',
 '24967.7925153182',
 '22452.9823753273',
 '..',
 '3993.03133624881',
 '505.421636114705',
 '801.990413888373',
 '23628.3272122367',
 '269.014984764581',
 '..',
 '12549.036894906',
 '19275.4733376066',
 '5041.01223518709',
 '..',
 '1550.36036555447',
 '336.154020658897',
 '319.957449358104',
 '955.665380611907',
 '735.521117948839',
 '1133.18637171644',
 '25230.2163329516',
 '5276.03318905496',
 '28897.4439396908',
 '451.572997293746',
 '748.257608719846',
 '1909.41230644823',
 '1494.38880236281',
 '28282.409882073',
 '21351.116935905',
 '20316.2480483237',
 '20500.9543995672',
 '3437.65551653148',
 '34406.1824638092',
 '1720.36142731527',
 '1490.92708987166',
 '395.329471608887',
 '735.069106401359',
 '..',
 '11561.2483689073',
 '..',
 '16587.2486486214',
 '308.409611591149',
 '326.941786715295',
 '3578.00190041351',
 '4422.38929245061',
 '405.605712148955',
 '306.710251570113',
 '6266.4898210897',
 '74287.4133739546',
 '3525.79363185461',
 '48440.1420151355',
 '15665.2979678214',
 '334.441617716753',
 '150.148942630026',
 '3913.42938647946',
 '3038.7814166818',
 '307.705828628661',
 '10402.233373566',
 '2389.06070685262',
 '646.1151155329',
 '3856.62522686864',
 '7544.56872335784',
 '2248.49211533078',
 '507.557658390849',
 '83724.465911527',
 '524.054008363595',
 '1909.59870186179',
 '1339.29406738281',
 '296.268406913079',
 '131.715298215255',
 '1950.64853633254',
 '..',
 '246.725558064189',
 '26896.5481111196',
 '15174.2774308861',
 '13882.8568268586',
 '1034.55138685018',
 '208.37705993638',
 '590.381815034907',
 '1823.02356104612',
 '..',
 '38542.715099709',
 '8475.96864264505',
 '544.494251402474',
 '8092.20732336256',
 '4046.42914824085',
 '515.684780393696',
 '1565.0542885389',
 '1941.47534195424',
 '990.565991260447',
 '4991.24435799511',
 '11734.7649743954',
 '18123.1987019918',
 '28517.2208367328',
 '1825.17980455979',
 '2100.3525390625',
 '238.788134020174',
 '1518.29369033585',
 '38730.8030430952',
 '524.669872100335',
 '8684.64576229464',
 '648.441473299398',
 '1727.28119565526',
 '7663.13708026446',
 '229.37565952613',
 '21700.0200458315',
 '..',
 '5722.1681828083',
 '10479.7596309273',
 '965.935499700581',
 '..',
 '2971.81976918833',
 '..',
 '15369.0011599444',
 '832.80357234611',
 '10283.032801538',
 '5642.7489037614',
 '..',
 '4282.69040253454',
 '456.624237060547',
 '1750.57673687227',
 '27247.857734793',
 '39727.8466713883',
 '5175.2619444591',
 '171.048064575398',
 '406.538757324219',
 '1893.26423865967',
 '529.778165896224',
 '292.823103529291',
 '1839.08686653094',
 '6939.82847117988',
 '2253.03485218065',
 '3142.92099774582',
 '774.482151976644',
 '16625.488923904',
 '1473.4158776561',
 '239.473127019302',
 '807.801940917969',
 '31280.7558649555',
 '27806.4488245133',
 '37133.623113437',
 '6284.45968003773',
 '456.706289511583',
 '1363.18505842973',
 '4986.67578837167',
 '404.807861229282',
 '..',
 '1335.55319529359',
 '550.360364536532',
 '382.941035235257',
 '568.386290532649']

In [18]:
df = df.replace('..', 0)

In [19]:
# df = df.dropna()
# df

In [20]:
df.dtypes

country_name    object
country_code    object
gpc_2001        object
gpc_2002        object
gpc_2003        object
gpc_2004        object
gpc_2005        object
gpc_2006        object
gpc_2007        object
gpc_2008        object
gpc_2009        object
gpc_2010        object
gpc_2011        object
gpc_2012        object
gpc_2013        object
gpc_2014        object
gpc_2015        object
gpc_2016        object
gpc_2017        object
gpc_2018        object
gpc_2019        object
dtype: object

In [21]:
df[['gpc_2001', 'gpc_2002','gpc_2003','gpc_2004','gpc_2005','gpc_2006',
    'gpc_2007','gpc_2008','gpc_2009','gpc_2010','gpc_2011','gpc_2012','gpc_2013',
    'gpc_2014','gpc_2015','gpc_2016','gpc_2017','gpc_2018','gpc_2019']] = df[['gpc_2001', 
    'gpc_2002','gpc_2003','gpc_2004','gpc_2005','gpc_2006','gpc_2007','gpc_2008','gpc_2009',
    'gpc_2010','gpc_2011','gpc_2012','gpc_2013','gpc_2014','gpc_2015','gpc_2016','gpc_2017',
    'gpc_2018','gpc_2019']].apply(pd.to_numeric)

In [22]:
df.dtypes

country_name     object
country_code     object
gpc_2001        float64
gpc_2002        float64
gpc_2003        float64
gpc_2004        float64
gpc_2005        float64
gpc_2006        float64
gpc_2007        float64
gpc_2008        float64
gpc_2009        float64
gpc_2010        float64
gpc_2011        float64
gpc_2012        float64
gpc_2013        float64
gpc_2014        float64
gpc_2015        float64
gpc_2016        float64
gpc_2017        float64
gpc_2018        float64
gpc_2019        float64
dtype: object

In [23]:
#b. format to nearest hundreth
df = df.round(2)
df

,country_name,country_code,gpc_2001,gpc_2002,gpc_2003,gpc_2004,gpc_2005,gpc_2006,gpc_2007,gpc_2008,...,gpc_2010,gpc_2011,gpc_2012,gpc_2013,gpc_2014,gpc_2015,gpc_2016,gpc_2017,gpc_2018,gpc_2019
country_name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Afghanistan,AFG,0.00,179.43,190.68,211.38,242.03,263.73,359.69,364.66,...,543.31,591.19,638.85,624.32,614.22,556.01,512.01,516.68,485.67,494.18
Albania,Albania,ALB,1281.66,1425.12,1846.12,2373.58,2673.79,2972.74,3595.04,4370.54,...,4094.35,4437.14,4247.63,4413.06,4578.63,3952.80,4124.06,4531.02,5287.66,5396.22
Algeria,Algeria,DZA,1740.61,1781.83,2103.38,2610.19,3113.09,3478.71,3950.51,4923.63,...,4480.79,5455.68,5592.22,5499.59,5493.06,4177.89,3946.45,4109.70,4142.02,3989.67
American Samoa,American Samoa,ASM,0.00,8666.66,8807.46,8528.25,8395.32,8340.52,8874.88,9740.82,...,10216.82,10223.30,11496.52,11450.72,11525.16,12059.64,12038.25,11003.83,11521.61,11715.36
Andorra,Andorra,AND,22970.51,25067.24,32272.85,37966.19,40064.22,42674.76,47804.85,48719.66,...,40849.76,43333.97,38684.57,39538.36,41302.38,35770.92,37474.75,38964.66,41793.32,40898.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands (U.S.),Virgin Islands (U.S.),VIR,0.00,30062.02,31731.26,35006.36,40828.75,41377.15,44158.51,39152.38,...,39905.13,38997.14,37795.32,34597.98,33045.36,34007.35,35324.97,35365.07,36653.86,38596.03
West Bank and Gaza,West Bank and Gaza,PSE,1335.55,1156.22,1257.70,1422.19,1543.70,1570.10,1664.25,2035.20,...,2557.08,2880.80,3067.44,3315.30,3352.11,3272.15,3527.61,3620.36,3562.33,3656.86
"Yemen, Rep.","Yemen, Rep.",YEM,550.36,579.85,620.38,709.97,832.84,921.42,1017.29,1229.25,...,1334.78,1374.62,1446.54,1607.15,1674.00,1601.81,1152.74,964.34,758.15,750.55
Zambia,Zambia,ZMB,382.94,382.24,435.46,538.59,702.74,1047.92,1124.29,1394.00,...,1489.46,1672.91,1763.07,1878.35,1762.43,1338.29,1280.81,1535.20,1516.37,1305.00
Zimbabwe,Zimbabwe,ZWE,568.39,530.53,478.01,483.00,476.56,447.85,431.79,356.69,...,948.33,1093.65,1304.97,1430.00,1434.90,1445.07,1464.59,1235.19,1254.64,1316.74

In [26]:
#export to csv
df.to_csv("Resources/cleaned_datasets/clean_GDP_per_capita.csv", index=False)