In [1]:
# Import Dependencies
import pandas as pd
import numpy as np

In [2]:
# Import Data file
health_exp = pd.read_csv("Resources/health_expenditure.csv")
health_exp_df = pd.DataFrame(health_exp)
health_exp_df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,9/16/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.0,2021.0
4,Aruba,ABW,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,Kosovo,XKX,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,"Yemen, Rep.",YEM,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.195936,4.960832,4.841805,4.252858,NaN,NaN,NaN,NaN,NaN,NaN
267,South Africa,ZAF,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355,NaN,NaN
268,Zambia,ZMB,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203,NaN,NaN
269,Zimbabwe,ZWE,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.918354,7.110148,8.133525,7.452066,7.675163,7.469752,8.680062,7.703565,NaN,NaN

In [3]:
# Droping the top 3 rows
health_exp_df = health_exp_df.drop(range(0,3))
health_exp_df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.0,2021.0
4,Aruba,ABW,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Africa Eastern and Southern,AFE,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.562794,6.565689,6.152063,6.482263,6.390654,6.317654,6.286829,6.266386,NaN,NaN
6,Afghanistan,AFG,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.897176,8.805941,9.528871,10.105348,11.818562,12.620817,14.126743,13.242202,NaN,NaN
7,Africa Western and Central,AFW,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.505065,3.621925,3.614749,3.834676,3.811248,3.789624,3.393160,3.366100,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,Kosovo,XKX,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,"Yemen, Rep.",YEM,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.195936,4.960832,4.841805,4.252858,NaN,NaN,NaN,NaN,NaN,NaN
267,South Africa,ZAF,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355,NaN,NaN
268,Zambia,ZMB,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203,NaN,NaN
269,Zimbabwe,ZWE,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.918354,7.110148,8.133525,7.452066,7.675163,7.469752,8.680062,7.703565,NaN,NaN

In [4]:
# Setting first column as Index
new_header = health_exp_df.iloc[0]
health_exp_df = health_exp_df[1:]
health_exp_df.columns = new_header
health_exp_df

3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
4,Aruba,ABW,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Africa Eastern and Southern,AFE,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.562794,6.565689,6.152063,6.482263,6.390654,6.317654,6.286829,6.266386,NaN,NaN
6,Afghanistan,AFG,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.897176,8.805941,9.528871,10.105348,11.818562,12.620817,14.126743,13.242202,NaN,NaN
7,Africa Western and Central,AFW,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.505065,3.621925,3.614749,3.834676,3.811248,3.789624,3.393160,3.366100,NaN,NaN
8,Angola,AGO,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.395750,2.732828,2.434129,2.605795,2.713149,2.791503,2.540102,2.533360,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,Kosovo,XKX,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,"Yemen, Rep.",YEM,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.195936,4.960832,4.841805,4.252858,NaN,NaN,NaN,NaN,NaN,NaN
267,South Africa,ZAF,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355,NaN,NaN
268,Zambia,ZMB,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203,NaN,NaN
269,Zimbabwe,ZWE,Current health expenditure (% of GDP),SH.XPD.CHEX.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.918354,7.110148,8.133525,7.452066,7.675163,7.469752,8.680062,7.703565,NaN,NaN

In [6]:
# Name of the columns
health_exp_df.columns

Index([  'Country Name',   'Country Code', 'Indicator Name', 'Indicator Code',
                 1960.0,           1961.0,           1962.0,           1963.0,
                 1964.0,           1965.0,           1966.0,           1967.0,
                 1968.0,           1969.0,           1970.0,           1971.0,
                 1972.0,           1973.0,           1974.0,           1975.0,
                 1976.0,           1977.0,           1978.0,           1979.0,
                 1980.0,           1981.0,           1982.0,           1983.0,
                 1984.0,           1985.0,           1986.0,           1987.0,
                 1988.0,           1989.0,           1990.0,           1991.0,
                 1992.0,           1993.0,           1994.0,           1995.0,
                 1996.0,           1997.0,           1998.0,           1999.0,
                 2000.0,           2001.0,           2002.0,           2003.0,
                 2004.0,           2005.0,           2006.0,           2007.0,
                 2008.0,           2009.0,           2010.0,           2011.0,
                 2012.0,           2013.0,           2014.0,           2015.0,
                 2016.0,           2017.0,           2018.0,           2019.0,
                 2020.0,           2021.0],
      dtype='object', name=3)

In [7]:
# Type of columns
health_exp_df.dtypes

3
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960.0            float64
                   ...
2017.0            float64
2018.0            float64
2019.0            float64
2020.0            float64
2021.0            float64
Length: 66, dtype: object

In [8]:
# Dropping the columns from year 1960 to 2000
health_exp_df = health_exp_df.drop(health_exp_df.columns[2:45], inplace = False, axis = 1)
health_exp_df

3,Country Name,Country Code,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,2007.0,2008.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,6.390627,5.969416,6.635666,6.710734,6.528098,6.492506,6.468483,6.299643,...,6.562794,6.565689,6.152063,6.482263,6.390654,6.317654,6.286829,6.266386,NaN,NaN
2,Afghanistan,AFG,NaN,9.443390,8.941258,9.808474,9.948290,10.622766,9.904675,10.256495,...,7.897176,8.805941,9.528871,10.105348,11.818562,12.620817,14.126743,13.242202,NaN,NaN
3,Africa Western and Central,AFW,3.770256,3.387634,4.681099,4.481882,4.277262,4.139578,3.908460,3.731591,...,3.505065,3.621925,3.614749,3.834676,3.811248,3.789624,3.393160,3.366100,NaN,NaN
4,Angola,AGO,4.483516,3.329461,3.547973,3.967201,2.852197,2.685537,2.974388,3.322905,...,2.395750,2.732828,2.434129,2.605795,2.713149,2.791503,2.540102,2.533360,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,4.945151,4.832372,5.757578,5.514405,5.205854,5.529299,5.820770,5.761911,...,5.195936,4.960832,4.841805,4.252858,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,7.939017,7.464463,7.915304,7.764534,7.689974,7.692216,7.681384,7.880248,...,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355,NaN,NaN
264,Zambia,ZMB,6.552485,6.794035,7.189994,7.049950,6.863322,5.873673,4.352650,4.012075,...,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203,NaN,NaN
265,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.918354,7.110148,8.133525,7.452066,7.675163,7.469752,8.680062,7.703565,NaN,NaN

In [17]:
# Dropping the 2021 column
health_exp_df = health_exp_df.drop(columns = health_exp_df.columns[21:22], inplace = False, axis = 1)
health_exp_df

,Country Name,Country Code,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,6.390627,5.969416,6.635666,6.710734,6.528098,6.492506,6.468483,6.299643,...,6.922891,6.773979,6.562794,6.565689,6.152063,6.482263,6.390654,6.317654,6.286829,6.266386
2,Afghanistan,AFG,NaN,9.443390,8.941258,9.808474,9.948290,10.622766,9.904675,10.256495,...,8.569672,8.561907,7.897176,8.805941,9.528871,10.105348,11.818562,12.620817,14.126743,13.242202
3,Africa Western and Central,AFW,3.770256,3.387634,4.681099,4.481882,4.277262,4.139578,3.908460,3.731591,...,3.521739,3.550677,3.505065,3.621925,3.614749,3.834676,3.811248,3.789624,3.393160,3.366100
4,Angola,AGO,4.483516,3.329461,3.547973,3.967201,2.852197,2.685537,2.974388,3.322905,...,2.695100,2.645608,2.395750,2.732828,2.434129,2.605795,2.713149,2.791503,2.540102,2.533360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,4.945151,4.832372,5.757578,5.514405,5.205854,5.529299,5.820770,5.761911,...,5.159331,4.769531,5.195936,4.960832,4.841805,4.252858,NaN,NaN,NaN,NaN
263,South Africa,ZAF,7.939017,7.464463,7.915304,7.764534,7.689974,7.692216,7.681384,7.880248,...,8.665970,8.741462,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355
264,Zambia,ZMB,6.552485,6.794035,7.189994,7.049950,6.863322,5.873673,4.352650,4.012075,...,3.719296,3.460532,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203
265,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.475839,8.081738,6.918354,7.110148,8.133525,7.452066,7.675163,7.469752,8.680062,7.703565

In [18]:
health_exp_df.columns

Index(['Country Name', 'Country Code', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019'],
      dtype='object')

In [20]:
# Setting the Index
health_exp_df = health_exp_df.set_axis(['Country Name', 'Country Code', '2001', '2002', '2003', '2004', '2005',         
                                        '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', 
                                        '2015', '2016', '2017', '2018', '2019'], axis = 1)
health_exp_df

,Country Name,Country Code,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,6.390627,5.969416,6.635666,6.710734,6.528098,6.492506,6.468483,6.299643,...,6.922891,6.773979,6.562794,6.565689,6.152063,6.482263,6.390654,6.317654,6.286829,6.266386
2,Afghanistan,AFG,NaN,9.443390,8.941258,9.808474,9.948290,10.622766,9.904675,10.256495,...,8.569672,8.561907,7.897176,8.805941,9.528871,10.105348,11.818562,12.620817,14.126743,13.242202
3,Africa Western and Central,AFW,3.770256,3.387634,4.681099,4.481882,4.277262,4.139578,3.908460,3.731591,...,3.521739,3.550677,3.505065,3.621925,3.614749,3.834676,3.811248,3.789624,3.393160,3.366100
4,Angola,AGO,4.483516,3.329461,3.547973,3.967201,2.852197,2.685537,2.974388,3.322905,...,2.695100,2.645608,2.395750,2.732828,2.434129,2.605795,2.713149,2.791503,2.540102,2.533360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,"Yemen, Rep.",YEM,4.945151,4.832372,5.757578,5.514405,5.205854,5.529299,5.820770,5.761911,...,5.159331,4.769531,5.195936,4.960832,4.841805,4.252858,NaN,NaN,NaN,NaN
263,South Africa,ZAF,7.939017,7.464463,7.915304,7.764534,7.689974,7.692216,7.681384,7.880248,...,8.665970,8.741462,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355
264,Zambia,ZMB,6.552485,6.794035,7.189994,7.049950,6.863322,5.873673,4.352650,4.012075,...,3.719296,3.460532,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203
265,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.475839,8.081738,6.918354,7.110148,8.133525,7.452066,7.675163,7.469752,8.680062,7.703565

In [21]:
health_exp_df.count()

Country Name    266
Country Code    266
2001            232
2002            233
2003            235
2004            235
2005            235
2006            235
2007            235
2008            235
2009            235
2010            236
2011            237
2012            236
2013            235
2014            235
2015            235
2016            234
2017            235
2018            235
2019            234
dtype: int64

In [25]:
health_exp_df = health_exp_df.dropna()
health_exp_df

,Country Name,Country Code,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Africa Eastern and Southern,AFE,6.390627,5.969416,6.635666,6.710734,6.528098,6.492506,6.468483,6.299643,...,6.922891,6.773979,6.562794,6.565689,6.152063,6.482263,6.390654,6.317654,6.286829,6.266386
3,Africa Western and Central,AFW,3.770256,3.387634,4.681099,4.481882,4.277262,4.139578,3.908460,3.731591,...,3.521739,3.550677,3.505065,3.621925,3.614749,3.834676,3.811248,3.789624,3.393160,3.366100
4,Angola,AGO,4.483516,3.329461,3.547973,3.967201,2.852197,2.685537,2.974388,3.322905,...,2.695100,2.645608,2.395750,2.732828,2.434129,2.605795,2.713149,2.791503,2.540102,2.533360
6,Andorra,AND,5.865939,6.098399,5.639918,5.381253,5.739886,5.064504,5.028323,5.785686,...,6.580060,6.086336,6.126280,6.155028,6.131505,6.283535,6.305263,6.589455,6.751625,6.711585
7,Arab World,ARB,4.284498,4.266429,4.146222,3.831061,3.512280,3.480394,3.583434,3.409167,...,3.907031,3.918381,3.986920,4.241538,4.561971,5.103330,5.055784,5.308416,5.050736,5.085542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,Vanuatu,VUT,3.393388,3.904378,3.506919,3.539915,3.305286,3.321756,3.107856,3.138102,...,3.526561,3.598194,3.935628,4.392345,3.646688,4.321683,2.931301,2.762915,3.346379,3.360347
259,World,WLD,9.026567,9.368701,9.517152,9.419202,9.338652,9.258065,9.101544,9.097985,...,9.495277,9.379718,9.389614,9.367164,9.448242,9.737717,9.862693,9.766083,9.704847,9.830785
260,Samoa,WSM,3.933475,4.640519,4.285870,4.648935,4.762528,5.018382,4.871751,4.657481,...,5.291891,5.440127,5.079440,6.449572,6.607532,5.787550,5.425002,5.567507,5.471911,6.363094
263,South Africa,ZAF,7.939017,7.464463,7.915304,7.764534,7.689974,7.692216,7.681384,7.880248,...,8.665970,8.741462,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355
264,Zambia,ZMB,6.552485,6.794035,7.189994,7.049950,6.863322,5.873673,4.352650,4.012075,...,3.719296,3.460532,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203

In [27]:
# Resetting the index to Zero
health_exp_df = health_exp_df.reset_index(drop=True)
health_exp_df

,Country Name,Country Code,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Africa Eastern and Southern,AFE,6.390627,5.969416,6.635666,6.710734,6.528098,6.492506,6.468483,6.299643,...,6.922891,6.773979,6.562794,6.565689,6.152063,6.482263,6.390654,6.317654,6.286829,6.266386
1,Africa Western and Central,AFW,3.770256,3.387634,4.681099,4.481882,4.277262,4.139578,3.908460,3.731591,...,3.521739,3.550677,3.505065,3.621925,3.614749,3.834676,3.811248,3.789624,3.393160,3.366100
2,Angola,AGO,4.483516,3.329461,3.547973,3.967201,2.852197,2.685537,2.974388,3.322905,...,2.695100,2.645608,2.395750,2.732828,2.434129,2.605795,2.713149,2.791503,2.540102,2.533360
3,Andorra,AND,5.865939,6.098399,5.639918,5.381253,5.739886,5.064504,5.028323,5.785686,...,6.580060,6.086336,6.126280,6.155028,6.131505,6.283535,6.305263,6.589455,6.751625,6.711585
4,Arab World,ARB,4.284498,4.266429,4.146222,3.831061,3.512280,3.480394,3.583434,3.409167,...,3.907031,3.918381,3.986920,4.241538,4.561971,5.103330,5.055784,5.308416,5.050736,5.085542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,Vanuatu,VUT,3.393388,3.904378,3.506919,3.539915,3.305286,3.321756,3.107856,3.138102,...,3.526561,3.598194,3.935628,4.392345,3.646688,4.321683,2.931301,2.762915,3.346379,3.360347
224,World,WLD,9.026567,9.368701,9.517152,9.419202,9.338652,9.258065,9.101544,9.097985,...,9.495277,9.379718,9.389614,9.367164,9.448242,9.737717,9.862693,9.766083,9.704847,9.830785
225,Samoa,WSM,3.933475,4.640519,4.285870,4.648935,4.762528,5.018382,4.871751,4.657481,...,5.291891,5.440127,5.079440,6.449572,6.607532,5.787550,5.425002,5.567507,5.471911,6.363094
226,South Africa,ZAF,7.939017,7.464463,7.915304,7.764534,7.689974,7.692216,7.681384,7.880248,...,8.665970,8.741462,8.773108,8.855524,8.550915,8.790190,8.821429,8.722624,8.858297,9.109355
227,Zambia,ZMB,6.552485,6.794035,7.189994,7.049950,6.863322,5.873673,4.352650,4.012075,...,3.719296,3.460532,3.930529,4.690910,3.829242,4.435102,4.477207,4.376977,5.032715,5.312203

In [28]:
for country in health_exp_df['Country Name'].unique():
    print(country)

Africa Eastern and Southern
Africa Western and Central
Angola
Andorra
Arab World
United Arab Emirates
Argentina
Armenia
Antigua and Barbuda
Australia
Austria
Azerbaijan
Burundi
Belgium
Benin
Burkina Faso
Bangladesh
Bulgaria
Bahrain
Bahamas, The
Bosnia and Herzegovina
Belarus
Belize
Bolivia
Brazil
Barbados
Brunei Darussalam
Bhutan
Botswana
Central African Republic
Canada
Central Europe and the Baltics
Switzerland
Chile
China
Cote d'Ivoire
Cameroon
Congo, Dem. Rep.
Congo, Rep.
Colombia
Comoros
Cabo Verde
Costa Rica
Caribbean small states
Cuba
Cyprus
Czechia
Germany
Djibouti
Dominica
Denmark
Dominican Republic
Algeria
East Asia & Pacific (excluding high income)
Early-demographic dividend
East Asia & Pacific
Europe & Central Asia (excluding high income)
Europe & Central Asia
Ecuador
Egypt, Arab Rep.
Euro area
Eritrea
Spain
Estonia
Ethiopia
European Union
Fragile and conflict affected situations
Finland
Fiji
France
Micronesia, Fed. Sts.
Gabon
United Kingdom
Georgia
Ghana
Guinea
Gambia, The
Guinea-Bissau
Equatorial Guinea
Greece
Grenada
Guatemala
Guyana
High income
Honduras
Heavily indebted poor countries (HIPC)
Croatia
Haiti
Hungary
IBRD only
IDA & IBRD total
IDA total
IDA blend
Indonesia
IDA only
India
Ireland
Iran, Islamic Rep.
Iceland
Israel
Italy
Jamaica
Jordan
Japan
Kazakhstan
Kenya
Kyrgyz Republic
Cambodia
Kiribati
St. Kitts and Nevis
Korea, Rep.
Kuwait
Latin America & Caribbean (excluding high income)
Lao PDR
Lebanon
Liberia
St. Lucia
Latin America & Caribbean
Least developed countries: UN classification
Low income
Sri Lanka
Lower middle income
Low & middle income
Lesotho
Late-demographic dividend
Lithuania
Luxembourg
Latvia
Morocco
Monaco
Moldova
Madagascar
Maldives
Middle East & North Africa
Mexico
Marshall Islands
Middle income
North Macedonia
Mali
Malta
Myanmar
Middle East & North Africa (excluding high income)
Mongolia
Mozambique
Mauritania
Mauritius
Malawi
Malaysia
North America
Namibia
Niger
Nigeria
Nicaragua
Netherlands
Norway
Nepal
Nauru
New Zealand
OECD members
Oman
Other small states
Pakistan
Panama
Peru
Philippines
Palau
Papua New Guinea
Poland
Pre-demographic dividend
Portugal
Paraguay
Pacific island small states
Post-demographic dividend
Qatar
Romania
Russian Federation
Rwanda
South Asia
Saudi Arabia
Sudan
Senegal
Singapore
Solomon Islands
Sierra Leone
El Salvador
San Marino
Serbia
Sub-Saharan Africa (excluding high income)
Sub-Saharan Africa
Small states
Sao Tome and Principe
Suriname
Slovak Republic
Slovenia
Sweden
Eswatini
Seychelles
Chad
East Asia & Pacific (IDA & IBRD countries)
Europe & Central Asia (IDA & IBRD countries)
Togo
Thailand
Tajikistan
Turkmenistan
Latin America & the Caribbean (IDA & IBRD countries)
Middle East & North Africa (IDA & IBRD countries)
Tonga
South Asia (IDA & IBRD)
Sub-Saharan Africa (IDA & IBRD countries)
Trinidad and Tobago
Tunisia
Turkiye
Tuvalu
Tanzania
Uganda
Ukraine
Upper middle income
Uruguay
United States
Uzbekistan
St. Vincent and the Grenadines
Venezuela, RB
Vietnam
Vanuatu
World
Samoa
South Africa
Zambia