In [1]:
import pandas as pd
import os

In [2]:
file_path = ("Resources/GDP_growth.csv")

In [3]:
#read in df
GDP_growth = pd.read_csv(file_path)
df = pd.DataFrame(GDP_growth)
df.head(10)

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,9/16/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,...,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000
4,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.035375,6.429817,-0.020479,3.543630,2.116716,5.482371,1.267218,-2.085600,-22.318948,NaN
5,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,0.239594,7.980768,5.164334,4.579952,5.327717,...,0.923067,4.200209,3.984387,2.952845,2.217017,2.557135,2.485244,2.025941,-2.886856,4.303667
6,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,12.752287,5.600745,2.724543,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,NaN
7,Africa Western and Central,AFW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.848752,3.770220,7.272440,5.396349,4.049793,...,5.142997,6.104192,5.927355,2.745894,0.127844,2.317679,2.952190,3.202544,-0.897014,3.914799
8,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,8.540000,4.950000,4.820000,0.940000,-2.580000,-0.150000,-1.316312,-0.700000,-5.500000,0.700000
9,Albania,ALB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.417243,1.002018,1.774449,2.218726,3.314981,3.802227,4.019360,2.088063,-3.481630,8.544083

In [4]:
#get header rows
headers = []

In [5]:
#drop first 3 rows with no data
clean_df = df.iloc[3:, :]

#use new first row as headers
headers = clean_df.iloc[0]
clean_df = clean_df[1:]
clean_df.columns = headers

clean_df.head(10)

3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
4,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.035375,6.429817,-0.020479,3.543630,2.116716,5.482371,1.267218,-2.085600,-22.318948,NaN
5,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,0.239594,7.980768,5.164334,4.579952,5.327717,...,0.923067,4.200209,3.984387,2.952845,2.217017,2.557135,2.485244,2.025941,-2.886856,4.303667
6,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,12.752287,5.600745,2.724543,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,NaN
7,Africa Western and Central,AFW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.848752,3.770220,7.272440,5.396349,4.049793,...,5.142997,6.104192,5.927355,2.745894,0.127844,2.317679,2.952190,3.202544,-0.897014,3.914799
8,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,8.540000,4.950000,4.820000,0.940000,-2.580000,-0.150000,-1.316312,-0.700000,-5.500000,0.700000
9,Albania,ALB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.417243,1.002018,1.774449,2.218726,3.314981,3.802227,4.019360,2.088063,-3.481630,8.544083
10,Andorra,AND,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.974444,-3.547597,2.504466,1.434140,3.709678,0.346072,1.588765,2.015548,-11.183940,8.949418
11,Arab World,ARB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.074697,2.564217,2.348679,3.052634,3.175147,1.242608,2.363881,1.586319,-5.051383,3.530294
12,United Arab Emirates,ARE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.483792,5.053078,4.410085,5.060335,2.984216,2.373551,1.189856,3.411539,-6.134501,NaN
13,Argentina,ARG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,5.427843,-0.852022,-5.308197,10.130298,10.569433,...,-1.026420,2.405324,-2.512615,2.731160,-2.080328,2.818503,-2.617396,-2.025934,-9.895269,10.263761

In [6]:
# clean_df.columns
# clean_df.dtypes

#convert column names to string

In [7]:
clean_df.drop(columns=["Country Name", "Country Code"], inplace=True)


# clean_df.columns= clean_df(clean_df['1960.0', '1961.0'])


# clean_df = clean_df.loc'Country Name','Country Code','2001.0', '2002.0',           
# '2003.0',
#                  '2004.0',           '2005.0',           '2006.0',           '2007.0',
#                  '2008.0',           '2009.0',           '2010.0',           '2011.0',
#                  '2012.0',           '2013.0',           '2014.0',           '2015.0',
#                  '2016.0',           '2017.0',           '2018.0',           '2019.0',
#                  '2020.0']

In [8]:
clean_df

3,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,1966.0,1967.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
4,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.035375,6.429817,-0.020479,3.543630,2.116716,5.482371,1.267218,-2.085600,-22.318948,NaN
5,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,0.239594,7.980768,5.164334,4.579952,5.327717,3.912108,5.256810,...,0.923067,4.200209,3.984387,2.952845,2.217017,2.557135,2.485244,2.025941,-2.886856,4.303667
6,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.752287,5.600745,2.724543,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,NaN
7,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.848752,3.770220,7.272440,5.396349,4.049793,-1.787079,-9.546464,...,5.142997,6.104192,5.927355,2.745894,0.127844,2.317679,2.952190,3.202544,-0.897014,3.914799
8,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.540000,4.950000,4.820000,0.940000,-2.580000,-0.150000,-1.316312,-0.700000,-5.500000,0.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.712195,5.340908,3.348804,5.916270,5.571757,4.825690,3.406631,4.756831,-5.340275,9.127578
266,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.392886,4.823415,-0.188574,-27.994546,-9.375124,-5.071796,0.752448,1.400000,-8.500000,-2.061513
267,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.844734,6.177931,7.373709,7.939609,6.122798,4.438386,7.196523,...,2.396232,2.485468,1.413826,1.321862,0.664552,1.157947,1.487617,0.113054,-6.431975,4.914603
268,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,7.919697,...,7.597593,5.057232,4.697992,2.920375,3.776679,3.504336,4.034494,1.441306,-2.785055,3.572815
269,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,8.367009,...,16.665429,1.989493,2.376929,1.779873,0.755869,4.709492,4.824211,-6.144236,-6.248748,5.849420